#!/bin/sh
# @NAME@ @VERSION@ installer, generated by mpc-vst-plugins tools/release.py. Run on the device as root:
#   sh install.sh [-y] [-t <synths-dir>]
# Copies portable/@SKIN@/ (the skin, the plugin and its data as ONE folder) into a Synths folder (default /sdcard/Synths),
# backs up MPC.settings, registers the plugin from the folder's plugin-meta.xml with %payload-path% replaced by that
# Synths folder, and restarts MPC. An older install (same uid, or the old /sdcard/vst layout) is replaced, not
# duplicated: its .so and the packaged data are removed and the user's own files (USER_DATA below, if any) are moved
# into the plugin folder. Files the user added inside the folder are kept across upgrades. Safe to run again.
set -e
cd "$(dirname "$0")"
NAME='@NAME@'; SO='@SO_NAME@'; SKIN='@SKIN@'; UID_HEX='@UID@'; LEGACY_SO='@LEGACY_SO@'; USER_DATA='@USER_DATA@'; EXTRAS='@EXTRAS@'
SYNTHS=/sdcard/Synths; YES=0; DEFER=0
die() { echo "error: $*" >&2; exit 1; }
while [ $# -gt 0 ]; do
    case "$1" in
        -y) YES=1; shift ;;
        -n) DEFER=1; shift ;;   # a batch caller has stopped MPC and starts it again after the last plugin
        -t) [ -n "$2" ] || die "-t needs a folder"; SYNTHS="$2"; shift 2 ;;
        *) die "usage: sh install.sh [-y] [-n] [-t <synths-dir>]" ;;
    esac
done
case "$SYNTHS" in /*) ;; *) die "-t must be an absolute path" ;; esac
case "$SYNTHS" in *"&"*|*"|"*|*"\\"*) die "the Synths path may not contain & | or backslash" ;; esac
FILE="$SYNTHS/$SKIN/$SO"
OLDFILE="$MPC_LEGACY_ROOT$LEGACY_SO"   # MPC_LEGACY_ROOT is empty on a device; tests point it at a scratch folder
OLDROOT="$MPC_LEGACY_ROOT$(dirname "$LEGACY_SO")"   # the previous layout kept the data next to the .so, in /sdcard/vst
LEGACY=0; [ -f "$OLDFILE" ] && LEGACY=1; MIGRATED=""

# MPC_INSTALL_TEST=1 skips the device checks so tests can run against a copy of MPC.settings.
if [ -z "$MPC_INSTALL_TEST" ]; then
    [ "$(id -u)" = 0 ] || die "run as root"
    case "$(uname -m)" in armv7*) ;; *) die "this build is for 32-bit ARM MPC OS devices (Gen1); this one is $(uname -m)" ;; esac
    command -v systemctl >/dev/null || die "systemctl not found"
fi
SETTINGS="${MPC_SETTINGS:-$(ls /media/az01-internal/Settings/*/MPC.settings 2>/dev/null | head -n 1)}"
[ -n "$SETTINGS" ] && [ -f "$SETTINGS" ] || die "MPC.settings not found (not an MPC OS device?)"
[ -f "portable/$SKIN/plugin-meta.xml" ] || die "this package is damaged: portable/$SKIN is missing"
sha256sum -c SHA256SUMS >/dev/null 2>&1 || die "files damaged (SHA256SUMS mismatch): copy the folder again"
mkdir -p "$SYNTHS" || die "cannot create $SYNTHS"
grep -q "$SYNTHS" "$SETTINGS" || echo "warning: $SYNTHS isn't in MPC's SynthContentLocations; the skin may not show"

echo "Installing $NAME @VERSION@:"
echo "  $SYNTHS/$SKIN/ (skin, $SO and its data), and an entry in $SETTINGS"
if [ $YES = 0 ]; then
    if [ $DEFER = 1 ]; then msg="MPC must already be stopped."; else msg="MPC will be stopped and restarted. Save your project first."; fi
    printf "%s Continue? [y/N] " "$msg"
    read -r ok; case "$ok" in y|Y|yes) ;; *) echo "cancelled"; exit 1 ;; esac
fi

# MPC's service is acvs on stock firmware, inmusic-mpc on Hakai-enabled systems; use whichever exists (acvs if neither is found).
mpc_service() {
    if systemctl cat acvs >/dev/null 2>&1; then echo acvs
    elif systemctl cat inmusic-mpc >/dev/null 2>&1; then echo inmusic-mpc
    else echo acvs; fi
}
mpc_ctl() {   # stop | start; a test run logs the call to $MPC_TEST_LOG instead of touching MPC
    if [ -n "$MPC_INSTALL_TEST" ]; then [ -z "$MPC_TEST_LOG" ] || echo "$1" >> "$MPC_TEST_LOG"; return 0; fi
    systemctl "$1" "$(mpc_service)"
}
if [ $DEFER = 1 ]; then   # -n: the caller stops MPC before the first plugin and starts it after the last
    [ -n "$MPC_INSTALL_TEST" ] || ! pidof MPC >/dev/null || die "MPC is running: with -n stop it first (stop the MPC service first, see INSTALL.md)"
else
    mpc_ctl stop
    trap 'mpc_ctl start' EXIT
    if [ -z "$MPC_INSTALL_TEST" ]; then
        i=0; while pidof MPC >/dev/null && [ $i -lt 30 ]; do sleep 1; i=$((i + 1)); done
        pidof MPC >/dev/null && die "MPC did not stop"
    fi
fi

# 1. the folder: staged next to the target, the user's own files carried over, then swapped in
NEW="$SYNTHS/$SKIN"; STAGE="$SYNTHS/.$SKIN.new"; OLD="$SYNTHS/.$SKIN.old"
rm -rf "$STAGE" "$OLD"
cp -a "portable/$SKIN" "$STAGE"
SYNTHS_SED=$(printf '%s' "$SYNTHS" | sed 's/[|&\\]/\\&/g')   # the folder as a sed replacement (| & \ escaped)
for f in "$STAGE"/Presets/*.xpl; do   # shipped presets name the plugin with the same placeholder as plugin-meta.xml
    [ -f "$f" ] || continue
    sed "s|%payload-path%|$SYNTHS_SED|g" "$f" > "$f.new" && mv "$f.new" "$f"
done
if [ -f MODES ]; then   # a zip unpacked on Windows or copied file by file loses exec bits and symlinks: put them back
    TAB=$(printf '\t')
    while IFS=$TAB read -r kind rel target; do
        case "$rel" in ""|/*|..|../*|*/..|*/../*) continue ;; esac
        if [ -f "$STAGE/$rel" ] && [ ! -L "$STAGE/$rel" ]; then
            if [ "$kind" = x ]; then chmod 755 "$STAGE/$rel"
            elif [ "$kind" = l ]; then rm -f "$STAGE/$rel"; ln -s "$target" "$STAGE/$rel"; fi
        fi
    done < MODES
fi
for d in $USER_DATA; do
    if [ -e "$NEW/$d" ]; then          # an earlier install of this layout: its files win over the shipped ones
        rm -rf "$STAGE/$d"; mkdir -p "$(dirname "$STAGE/$d")"; cp -a "$NEW/$d" "$STAGE/$d"
    elif [ $LEGACY = 1 ] && [ -d "$OLDROOT/$d" ]; then   # the old layout: merged over what the package ships
        mkdir -p "$STAGE/$d"; cp -a "$OLDROOT/$d/." "$STAGE/$d/"; MIGRATED="$MIGRATED $d"
    fi
done
if [ -e "$NEW" ]; then mv "$NEW" "$OLD"; fi
mv "$STAGE" "$NEW"
rm -rf "$OLD"

# 2. the plugin-list entry: %payload-path% is the Synths folder; entries with the same file= or uid are replaced
BAK="$SETTINGS.bak-$(echo "$SO" | sed 's/\.so$//')-$(date +%Y%m%d-%H%M%S)"
cp "$SETTINGS" "$BAK"
sed "s|%payload-path%|$SYNTHS_SED|g" "portable/$SKIN/plugin-meta.xml" > "$SETTINGS.entry"
awk -v mode=add -v file="$FILE" -v alt="$LEGACY_SO" -v uid="$UID_HEX" -v entryfile="$SETTINGS.entry" -f plugin_list.awk "$SETTINGS" > "$SETTINGS.new"
rm -f "$SETTINGS.entry"
n=$(grep -c "file=\"$FILE\"" "$SETTINGS.new" || true)
u=$(grep -c " uid=\"$UID_HEX\"" "$SETTINGS.new" || true)
[ "$n" = 1 ] && [ "$u" = 1 ] || { rm -f "$SETTINGS.new"; die "settings edit failed (entries: $n by file, $u by uid); MPC.settings unchanged"; }
# without python3 (it may be absent on the device) at least make sure the file still has its root element
grep -q '<PROPERTIES' "$SETTINGS.new" && grep -q '</PROPERTIES>' "$SETTINGS.new" ||
    { rm -f "$SETTINGS.new"; die "edited settings lost their root element; MPC.settings unchanged"; }
if command -v python3 >/dev/null; then
    python3 -c 'import sys, xml.etree.ElementTree as E; E.parse(sys.argv[1])' "$SETTINGS.new" 2>/dev/null ||
        { rm -f "$SETTINGS.new"; die "edited settings aren't valid XML; MPC.settings unchanged"; }
fi
mv "$SETTINGS.new" "$SETTINGS"

# 3. an old install of the same plugin in the previous layout: its .so, the data the package shipped, and (already copied
#    into the plugin folder above) the user's own files. Nothing is removed before the new install is in place.
if [ $LEGACY = 1 ] && [ "$LEGACY_SO" != "$FILE" ]; then
    rm -f "$OLDFILE" && echo "removed the old copy $LEGACY_SO"
    for d in $MIGRATED; do
        rm -rf "$OLDROOT/$d" && echo "moved your files from $(dirname "$LEGACY_SO")/$d into $SYNTHS/$SKIN"
    done
    for e in $EXTRAS; do
        case " $USER_DATA " in *" $e "*) continue ;; esac
        if [ -e "$OLDROOT/$e" ]; then rm -rf "$OLDROOT/$e" && echo "removed the old packaged data $(dirname "$LEGACY_SO")/$e"; fi
    done
fi
sync

echo "Done. Settings backup: $BAK"
echo "Starting MPC. Add '$NAME' to a track from the plugin browser."
