#!/bin/sh
# @NAME@ uninstaller, generated by mpc-vst-plugins tools/release.py. Run on the device as root:
#   sh uninstall.sh [-y] [-t <synths-dir>]
# Stops MPC, removes the plugin's folder from the Synths folder (default /sdcard/Synths) and its MPC.settings entry
# (after a backup), and starts MPC again. Files the user added (listed in USER_DATA below, if any) are kept.
set -e
cd "$(dirname "$0")"
NAME='@NAME@'; SO='@SO_NAME@'; SKIN='@SKIN@'; UID_HEX='@UID@'; LEGACY_SO='@LEGACY_SO@'; USER_DATA='@USER_DATA@'
SYNTHS=/sdcard/Synths; YES=0; DEFER=0
die() { echo "error: $*" >&2; exit 1; }
while [ $# -gt 0 ]; do
    case "$1" in
        -y) YES=1; shift ;;
        -n) DEFER=1; shift ;;   # a batch caller has stopped MPC and starts it again after the last plugin
        -t) [ -n "$2" ] || die "-t needs a folder"; SYNTHS="$2"; shift 2 ;;
        *) die "usage: sh uninstall.sh [-y] [-n] [-t <synths-dir>]" ;;
    esac
done
case "$SYNTHS" in /*) ;; *) die "-t must be an absolute path" ;; esac
FILE="$SYNTHS/$SKIN/$SO"
OLDFILE="$MPC_LEGACY_ROOT$LEGACY_SO"   # MPC_LEGACY_ROOT is empty on a device; tests point it at a scratch folder

if [ -z "$MPC_INSTALL_TEST" ]; then
    [ "$(id -u)" = 0 ] || die "run as root"
    command -v systemctl >/dev/null || die "systemctl not found"
fi
SETTINGS="${MPC_SETTINGS:-$(ls /media/az01-internal/Settings/*/MPC.settings /data/Settings/*/MPC.settings 2>/dev/null | head -n 1)}"
[ -n "$SETTINGS" ] && [ -f "$SETTINGS" ] || die "MPC.settings not found"
if [ $YES = 0 ]; then
    if [ $DEFER = 1 ]; then msg="MPC must already be stopped."; else msg="MPC will be stopped and restarted. Save your project first."; fi
    printf "Remove %s? %s [y/N] " "$NAME" "$msg"
    read -r ok; case "$ok" in y|Y|yes) ;; *) echo "cancelled"; exit 1 ;; esac
fi

# MPC's service is acvs on stock firmware, inmusic-mpc on Hakai-enabled systems; use whichever exists (acvs if neither is found).
mpc_service() {
    if systemctl cat acvs >/dev/null 2>&1; then echo acvs
    elif systemctl cat inmusic-mpc >/dev/null 2>&1; then echo inmusic-mpc
    else echo acvs; fi
}
mpc_ctl() {   # stop | start; a test run logs the call to $MPC_TEST_LOG instead of touching MPC
    if [ -n "$MPC_INSTALL_TEST" ]; then [ -z "$MPC_TEST_LOG" ] || echo "$1" >> "$MPC_TEST_LOG"; return 0; fi
    systemctl "$1" "$(mpc_service)"
}
if [ $DEFER = 1 ]; then   # -n: the caller stops MPC before the first plugin and starts it after the last
    [ -n "$MPC_INSTALL_TEST" ] || ! pidof MPC >/dev/null || die "MPC is running: with -n stop it first (stop the MPC service first, see INSTALL.md)"
else
    mpc_ctl stop
    trap 'mpc_ctl start' EXIT
    if [ -z "$MPC_INSTALL_TEST" ]; then
        i=0; while pidof MPC >/dev/null && [ $i -lt 30 ]; do sleep 1; i=$((i + 1)); done
        pidof MPC >/dev/null && die "MPC did not stop"
    fi
fi

BAK="$SETTINGS.bak-$(echo "$SO" | sed 's/\.so$//')-$(date +%Y%m%d-%H%M%S)"
cp "$SETTINGS" "$BAK"
awk -v mode=remove -v file="$FILE" -v alt="$LEGACY_SO" -v uid="$UID_HEX" -f plugin_list.awk "$SETTINGS" > "$SETTINGS.new"
n=$(grep -c " uid=\"$UID_HEX\"" "$SETTINGS.new" || true)
[ "$n" = 0 ] || { rm -f "$SETTINGS.new"; die "settings edit failed; MPC.settings unchanged"; }
# without python3 (it may be absent on the device) at least make sure the file still has its root element
grep -q '<PROPERTIES' "$SETTINGS.new" && grep -q '</PROPERTIES>' "$SETTINGS.new" ||
    { rm -f "$SETTINGS.new"; die "edited settings lost their root element; MPC.settings unchanged"; }
if command -v python3 >/dev/null; then
    python3 -c 'import sys, xml.etree.ElementTree as E; E.parse(sys.argv[1])' "$SETTINGS.new" 2>/dev/null ||
        { rm -f "$SETTINGS.new"; die "edited settings aren't valid XML; MPC.settings unchanged"; }
fi
mv "$SETTINGS.new" "$SETTINGS"

# the folder goes, except files the user added
DIR="$SYNTHS/$SKIN"; KEEP="$SYNTHS/.$SKIN.keep"
if [ -d "$DIR" ]; then
    rm -rf "$KEEP"
    for d in $USER_DATA; do
        if [ -e "$DIR/$d" ]; then mkdir -p "$(dirname "$KEEP/$d")"; mv "$DIR/$d" "$KEEP/$d"; fi
    done
    rm -rf "$DIR"
    if [ -d "$KEEP" ]; then mv "$KEEP" "$DIR"; echo "kept your own files in $DIR"; fi
fi
if [ "$LEGACY_SO" != "$FILE" ]; then rm -f "$OLDFILE"; fi
sync
echo "Removed $NAME. Settings backup: $BAK"
